//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise2_050_AdelinaYogaEkaSafira.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITI_UMY")]
    public interface ITI_UMY {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        Service_050_AdelinaYogaEkaSafira.Mahasiswa[] GetAllMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        System.Threading.Tasks.Task<Service_050_AdelinaYogaEkaSafira.Mahasiswa[]> GetAllMahasiswaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        Service_050_AdelinaYogaEkaSafira.Mahasiswa GetMahasiswaByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        System.Threading.Tasks.Task<Service_050_AdelinaYogaEkaSafira.Mahasiswa> GetMahasiswaByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        string CreateMahasiswa(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CreateMahasiswaAsync(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaByNIMResponse")]
        string UpdateMahasiswaByNIM(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaByNIMResponse")]
        System.Threading.Tasks.Task<string> UpdateMahasiswaByNIMAsync(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/DeleteMahasiswaResponse")]
        string DeleteMahasiswa(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/DeleteMahasiswaResponse")]
        System.Threading.Tasks.Task<string> DeleteMahasiswaAsync(string nim);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITI_UMYChannel : Exercise2_050_AdelinaYogaEkaSafira.ServiceReference1.ITI_UMY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TI_UMYClient : System.ServiceModel.ClientBase<Exercise2_050_AdelinaYogaEkaSafira.ServiceReference1.ITI_UMY>, Exercise2_050_AdelinaYogaEkaSafira.ServiceReference1.ITI_UMY {
        
        public TI_UMYClient() {
        }
        
        public TI_UMYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service_050_AdelinaYogaEkaSafira.Mahasiswa[] GetAllMahasiswa() {
            return base.Channel.GetAllMahasiswa();
        }
        
        public System.Threading.Tasks.Task<Service_050_AdelinaYogaEkaSafira.Mahasiswa[]> GetAllMahasiswaAsync() {
            return base.Channel.GetAllMahasiswaAsync();
        }
        
        public Service_050_AdelinaYogaEkaSafira.Mahasiswa GetMahasiswaByNIM(string nim) {
            return base.Channel.GetMahasiswaByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<Service_050_AdelinaYogaEkaSafira.Mahasiswa> GetMahasiswaByNIMAsync(string nim) {
            return base.Channel.GetMahasiswaByNIMAsync(nim);
        }
        
        public string CreateMahasiswa(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswa(mhs);
        }
        
        public System.Threading.Tasks.Task<string> CreateMahasiswaAsync(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswaAsync(mhs);
        }
        
        public string UpdateMahasiswaByNIM(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs) {
            return base.Channel.UpdateMahasiswaByNIM(mhs);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMahasiswaByNIMAsync(Service_050_AdelinaYogaEkaSafira.Mahasiswa mhs) {
            return base.Channel.UpdateMahasiswaByNIMAsync(mhs);
        }
        
        public string DeleteMahasiswa(string nim) {
            return base.Channel.DeleteMahasiswa(nim);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMahasiswaAsync(string nim) {
            return base.Channel.DeleteMahasiswaAsync(nim);
        }
    }
}
